FROM php:7.4-apache

# Copy source code
COPY src/ /var/www/html/

# Install required packages
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Expose port
EXPOSE 80